# SPDX-License-Identifier: MIT
# Scanner reference read by scripts/audit-image.mjs; Dependabot maintains this pin.
FROM aquasec/trivy:0.75.0@sha256:af6acf9a6b85dfe389a1941505c0ce9efef52a4719635e1a962f022a3d855daa
